"""Validate tickers in `stock_symbols_220.py` by checking 1-month history via yfinance.

This script reads the symbol file as text (no import), extracts `STOCK_SYMBOLS`,
verifies each symbol has at least one recent data point using yfinance, and writes back a cleaned
`stock_symbols_220.py` preserving only the good symbols.
"""
import time
import re
import os
import sys
import yfinance as yf

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

ROOT = os.path.dirname(os.path.dirname(__file__))
SYMBOL_FILE = os.path.join(ROOT, 'stock_symbols_220.py')


def load_symbols_from_file(path):
    if not os.path.exists(path):
        return []
    src = open(path, 'r', encoding='utf-8').read()
    # naive exec in a restricted namespace
    ns = {}
    try:
        exec(src, {}, ns)
    except Exception:
        # fallback: regex parse
        m = re.search(r"STOCK_SYMBOLS\s*=\s*\[([^\]]*)\]", src, re.S)
        if not m:
            return []
        items = re.findall(r"['\"]([A-Z0-9\.\-]{1,6})['\"]", m.group(1))
        return items
    return ns.get('STOCK_SYMBOLS', [])


def write_symbols(path, symbols):
    with open(path, 'w', encoding='utf-8') as f:
        f.write('# Auto-cleaned list generated by scripts/validate_symbols.py\n')
        f.write('STOCK_SYMBOLS = [\n')
        for s in symbols:
            f.write(f"    \"{s}\",\n")
        f.write(']\n')


def validate_symbols(symbols):
    good = []
    bad = []

    for i, s in enumerate(symbols, 1):
        try:
            # Get quote via yfinance
            ticker = yf.Ticker(s)
            hist = ticker.history(period="1d")
            
            if not hist.empty:
                price = hist['Close'].iloc[-1]
                good.append(s)
                print(f"[{i}/{len(symbols)}] GOOD: {s} (price={price:.2f})")
            else:
                bad.append(s)
                print(f"[{i}/{len(symbols)}] BAD: {s} (no valid data)")
        except Exception as e:
            bad.append(s)
            print(f"[{i}/{len(symbols)}] ERROR: {s} -> {e}")
        time.sleep(0.1)  # Respect rate limits

    return good, bad


def main():
    symbols = load_symbols_from_file(SYMBOL_FILE)
    print(f"Loaded {len(symbols)} symbols from {SYMBOL_FILE}")
    if not symbols:
        print('No symbols found. Consider running scripts/build_sp500_220.py first.')
        write_symbols(SYMBOL_FILE, [])
        return

    good, bad = validate_symbols(symbols)
    print(f"\nValidation complete!")
    print(f"Good: {len(good)}; Bad: {len(bad)}")
    write_symbols(SYMBOL_FILE, good)
    print(f"Wrote cleaned list to: {SYMBOL_FILE}")


if __name__ == '__main__':
    main()
